name: Switch Validation

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:20241023
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          sudo apt-get remove -y cmake
          git -C libultraship remote add nx https://github.com/Net64DD/libultraship.git
          git -C libultraship fetch nx
          git -C libultraship checkout nx/main-nx
          wget https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.sh -O /tmp/cmake.sh
          sudo sh /tmp/cmake.sh --prefix=/usr/local/ --exclude-subdir
          cmake -H. -Bbuild-switch -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
          cmake --build build-switch --config Release -j3
          wget -O gamecontrollerdb.txt https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt
          mv README.md readme.txt
          mv build-switch/*.nro Starship.nro
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Starship-switch
          retention-days: 1
          path: |
            Starship.nro
            config.yml
            assets
            gamecontrollerdb.txt